name: Release Preparation
description: Prepare Mesh Release
title: "Prepare Release <Version>"
labels: []
projects: []
body:
  - type: input
    id: release-date
    attributes:
      label: Planned Date
    validations:
      required: true
  - type: input
    id: responsible
    attributes:
      label: Release Captain
    validations:
      required: true
  - type: textarea
    id: todo-list
    attributes:
      label: To Do
      value: |
        - [ ] Bump version 
        - [ ] Bump TeamCity version numbers 
        - [ ] Build https://teamcity-deploy.voluead.volue.com/buildConfiguration
        - [ ] Pin & tag
        - [ ] Install on test servers
        - [ ] Smoke test
        - [ ] Publish to [Sharepoint](https://volue.sharepoint.com/:f:/r/sites/SmartEnergyRD4543/Delte%20dokumenter/Release%20management/Distribution_Artifacts/Official_Releases/SeparateReleases/Mesh/)
        - [ ] Create patch note PDF @raos-tw
        - [ ] Check if new model should be included 
        - [ ] [Announce](https://teams.microsoft.com/l/message/19:MnuQdrGhFqaQjTZe3gtV6HEj_qSZRVR-SMyEx5lpezs1@thread.tacv2/1679916139303?tenantId=9ce76d42-5ecb-4d8f-939b-a462ad28cf34&groupId=66703af7-8520-4e05-897e-f4a8f34819e3&parentMessageId=1679916139303&teamName=Energy%20-%20Mesh&channelName=General&createdTime=1679916139303&allowXTenantAccess=false)
      render: markdown
    validations:
      required: true

  - type: textarea
    id: test-servers
    attributes:
      label: Test Servers
      placeholder: |
        - [ ] Install on `tdtrhopttrunka3.voluead.volue.com`
    validations:
      required: true
  