name: Release Preparation
description: Prepare Mesh Release
title: "Prepare Release <Version>"
labels: []
projects: []
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "
        - [ ] Bump version to <Version>
        "
      render: markdown
    validations:
      required: true
  