name: Release Preparation
description: Prepare Mesh Release
title: "Prepare Release <Version>"
labels: []
projects: []
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ""
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      render: markdown
      value: |
      - [x] Bump version to <Version>
      - [x] Bump TeamCity version numbers to <Version>
      - [x] Build https://teamcity-deploy.voluead.volue.com/buildConfiguration/Mesh_Releases_Mesh29/636638
      - [x] Pin & tag
      - [x] Install on `tdtrhopttrunka3.voluead.volue.com`
      - [x] Install on `tdtrhopttrunka4.voluead.volue.com`
      - [x] Install on `tdtrhsmg125ha2.voluead.volue.com`
      - [x] Install on `tdtrhsmg126a2.voluead.volue.com`
      - [x] Install on `tdtrhopt111A.voluead.volue.com`
      - [x] Smoke test
      - [x] Publish to https://volue.sharepoint.com/:f:/r/sites/SmartEnergyRD4543/Delte%20dokumenter/Release%20management/Distribution_Artifacts/Official_Releases/SeparateReleases/Mesh/2.9
      - [x] Create patch note PDF @raos-tw
      - [x] Check if new model should be included ...
      - [x] [Announce](https://teams.microsoft.com/l/message/19:MnuQdrGhFqaQjTZe3gtV6HEj_qSZRVR-SMyEx5lpezs1@thread.tacv2/1679916139303?tenantId=9ce76d42-5ecb-4d8f-939b-a462ad28cf34&groupId=66703af7-8520-4e05-897e-f4a8f34819e3&parentMessageId=1679916139303&teamName=Energy%20-%20Mesh&channelName=General&createdTime=1679916139303&allowXTenantAccess=false)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true