on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test1
        id: test1
        uses: simia/pr-content-validation@v1.1
        with:
          relese-notes-ignore-pattern: 'TEST1'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.test1.outputs.time }}"