on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]
  pull_request_review_comment:
    types: [created, edited, deleted]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test
    if: ${{ github.event.issue.pull_request || github.event.pull_request}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:      
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: test
      - name: test1
        id: test1
        uses: simia/pr-content-validation@v1.1
        with:
          relese-notes-ignore-pattern: 'TEST1'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.test1.outputs.time }}"