name: Notify on Closed Issue

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check issue labels
        id: check_labels
        uses: actions/github-script@v5
        with:
          script: |
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            return {
              hasBugLabel: issue.data.labels.some(label => label.name === 'bug'),
              hasFeatureLabel: issue.data.labels.some(label => label.name === 'feature')
            }

      - name: Notify team
        if: steps.check_labels.outputs.hasBugLabel || steps.check_labels.outputs.hasFeatureLabel
        uses: actions/github-script@v5
        with:
          script: |
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const issueUrl = issue.data.html_url;
            const issueTitle = issue.data.title;
            const issueLabels = issue.data.labels.map(label => label.name).join(', ');

            const teamSlug = 'your-team-slug'; // Replace with the slug of your team
            const notificationMessage = `The issue "${issueTitle}" (${issueUrl}) with labels: ${issueLabels} has been closed.`;

            const usersToNotify = ['simia'];

            for (const user of usersToNotify) {
              await github.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `@${user} ${notificationMessage}`
              });
            }

