name: Notify on Closed Issue

on:
  issues:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check issue labels
        id: check_labels
        uses: actions/github-script@v5
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            return {
              hasSupportLabel: issue.data.labels.some(label => label.name === 'support'),
              
            }

      - name: Notify team
        if: steps.check_labels.outputs.hasSupportLabel
        uses: actions/github-script@v5
        with:
          script: |
            const issue = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const issueUrl = issue.data.html_url;
            const issueTitle = issue.data.title;
            const issueLabels = issue.data.labels.map(label => label.name).join(', ');

            const teamSlug = 'your-team-slug'; // Replace with the slug of your team
            const notificationMessage = `The issue "${issueTitle}" (${issueUrl}) with labels: ${issueLabels} has been closed.`;

            users=("simia")  # Replace with the GitHub usernames of the users to notify
            notification_message="The issue \"$issue_title\" ($issue_url) with labels: $issue_labels has been closed."
          
            for user in "${users[@]}"; do
              curl -sSL -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -d "{\"body\": \"$notification_message\"}" \
                "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments" > /dev/null
            done

